### ISSUE TITLE
[Image] Profile picture not loading

### ISSUE THREAD

**Issue by jecabahug** [seeej/digiwiz#19]
Profile picture of user is not loading on Enrollment Requests page and View Results page .

See image below for reference.

![Enrollment Requests](https://user-images.githubusercontent.com/33801934/59773423-29047b80-92e0-11e9-80e2-6e0155ef7cf4.PNG)
![Quiz Results](https://user-images.githubusercontent.com/33801934/59773425-299d1200-92e0-11e9-8409-1936f19fe4ce.PNG)

**Comment by seeej** [comment]
The thumbnail images were just not pushed to the repo. This works fine.
